# Token types
TT_KEYWORD = "KEYWORD"
TT_STRING = "STRING"
TT_IDENTIFIER = "IDENTIFIER"
TT_OPERATOR = "OPERATOR"
TT_NUMBER = "NUMBER"
# Additional token types
TT_ASSIGN = "ASSIGN"
TT_EQUALS = "EQUALS"
